---
title: "Arrange Full RNA Dataset"
author: "Holly Giles"
date: "7/28/2021"
output: html_document
---

```{r}
library(DESeq2)
library(dplyr)

load("ddsrna_180717.RData")
load("../../data/patMeta.RData")

#PatientID key 
load("/Volumes/huber/users/giles/projects/publications/cytokine_screen_2020/vignettes/Finalised/data/individual_datasets/PatientIDkeys/Pat_ID_key.Rdata")
```


```{r RNAdata all samples}

#1. Make counts matrix  for patients in Cytokine Screen 2020 only
#subset for patients in screen 
dds.smp <- dds[, which(colData(dds)[,"PatID"] %in% unique(Patients$PatientID))]

#get counts matrix, rowdata and coldata  
ctsMat.smp <- counts(dds.smp)

coldata.smp <- as.data.frame(colData(dds.smp))

rowdata.smp <- rowData(dds.smp)

#2. Arrange meta data
#add new anonymised patient IDs
coldata.smp <- 
  left_join(coldata.smp, Patients, by= c( "PatID" = "PatientID"))

#subset for columns on interest
coldata.smp <-
  coldata.smp[,c( "Patient", "PatID")]

#rename columns
colnames(coldata.smp) <- c( "PatientID", "origPatID")

coldata.smp <- 
  left_join(coldata.smp, patMeta, by = "PatientID") 



#3. Arrange counts matrix
#make sure call patients in colData are in counts matrix
all(coldata.smp[,"origPatID"] %in% colnames(ctsMat.smp))

#put counts in same order as columns of coldata
ctsMat.smp <- ctsMat.smp[, coldata.smp[,"origPatID"]]

#remove old Patient IDs
colnames(ctsMat.smp) <- coldata.smp[,"PatientID"]

coldata.smp <- select(coldata.smp, -origPatID)

#4. Make new dds dataset with new counts matrix and coldata
dds.smp <- DESeqDataSetFromMatrix(ctsMat.smp, coldata.smp, design =~1)

#5. Add rowdata
rowData(dds.smp) <- rowdata.smp

dds_smp_full <- dds.smp

save(dds_smp_full, file = "../../data/dds_smp_full.RData")


```