# Results

 
Chapter 6: Molecular and microenvironmental modulators of drug response in CLL
The effect of microenvironmental stimuli on drug response
Key result: Map of drug - stimuli interactions 
Key result: Classification of drug-stimuli interaction types (antagonistic / synergistic, positive / negative)  
Key result: Discussion of key examples including Ibrutinib + IL4, Ibrutinib + IFNgamma, Ralimetinib + IFNgamma, Ibrutinib + Resiquimod  
The effect of genetic features on drug response: 
Key result: Map of genetic modulators of drug response
Key result: discussion of examples including:
IBET-762 and trisomy 12
Nutlin-3a and trisomy 12 and gene dosage effect of MDM2 in trisomy12 CLL
Correlation of IBET-762 and Nutlin-3a
Ralimetinib and trisomy 12
The modulatory effect of mutations on drug - stimuli interactions: 
Key result: Map of drug - stimuli - gene interactions 
Key result: Discussion of examples including:
Responses to chemotherapeutic drugs in the context of TLR stimulation are modulated by del11q and ATM mutations,
Trisomy12 enhances pro-survival synergy between Ralimetinib + IFNgamma
Ralimetinib treatment increases the pro-survival effect of IL4, and this is further enhanced in NOTCH1 and Ras/Raf mutants
Fludarabine and TLR
Ibrutinib and IL4
Discuss examples in drug- cyt -gene examples script 
Can stimuli + genes predict drug response - this would be useful in the clinic. Especially if its just TLR/IL4 response, are specific signals useful?

_Equation \@ref(eq:drugCytInt) quantifies how the viability with any combination can be predicted:_
    \begin{equation}
            log(V) = \beta_{drug}X_{drug} + \beta_{stimulus}X_{stimulus} + \beta_{int}X_{drug}X_{stimulus} + \epsilon
                                       (\#eq:drugCytInt)
    \end{equation}
    
_where $V$ is the viability with a given treatment,_ $\beta_{drug}$, $\beta_{stimulus}$ _and_ $\beta_{int}$ _are coefficients for the drug, stimulus and combinatorial terms and_ $X_{drug}$ _and_ $X_{stimulus}$  _are indicator variables (0 or 1) for the presence or absence of a drug/stimulus._ $\epsilon$ _is the vector of model residuals._
    


