# Discussion
TLR and SPIB - perhaps they orperate via nfkb - manymutations centre on nfkb1:
https://pubmed.ncbi.nlm.nih.gov/25733685/
also nfkb1 is higher in trisomy 12 at rna and protein level 



Also check out my ideas on NOS 


TLR couldbeprognostics 
the fact taht MYD88 mutations in TLR signalling are excluvisvely in IGHVM patients suggests they are only of advantage in IGHVM -perhaps they make TLR signalling pro-sruvival(or at least not toxic) 

 In addition, the MYD88 gene is mutated in ~3% of patients with CLL, exclusively those with IGHV-M CLL40,41 (Fig. 2; Table 1). MYD88, a cytosolic protein adaptor involved in the Toll-like receptor (TLR) pathway, has pleiotropic functions in B cells, including NF-κB activation.
 
 only tirsomy 12 and MYD88 mutations are linked to a distinct epigenetic profile: 
 https://www.nature.com/articles/s41591-018-0028-4


TLR modulation could be prognostic - it is modualted by ATM and del11q- this coudl explain: 
Austen, B., Powell, J. E., Alvi, A., Edwards, I., Hooper, L., Starczynski, J., Taylor, A. M. R.,
Fegan, C., Moss, P. and Stankovic, T. (2005). Mutations in the ATM gene lead to impaired
overall and treatment-free survival that is independent of IGVH mutation status in patients
with B-CLL. Blood 106, 3175–82

TLR Signaling Is Activated in Lymph Node–Resident CLL Cells and Is Only Partially Inhibited by Ibrutinib
Eman L. Dadashian
https://cancerres.aacrjournals.org/content/79/2/360.short

tlr and fludarabine: 
n Vitro Sensitivity of CLL Cells to Fludarabine May Be Modulated by the Stimulation of Toll-like Receptors
Eleonora Fonte


 Expression and function of toll like receptors in chronic lymphocytic leukaemia cells
Marta Muzio  1 , Cristina Scielzo, Maria T S Bertilaccio, Michela Frenquelli, Paolo Ghia, Federico Caligaris-Cappio


In Vivo TLR Signaling - from HAselager

Recurrent mutations in CLL include MYD88, a gene which encodes a downstream component of TLR signaling (69). TLRs are part of the innate immune system and respond to specific molecular patterns found in various microorganisms, including bacteria (43). These receptors are expressed in CLL cells and biologically active, suggesting an additional route of stimulation besides BCR signaling (69). TLR signaling leads to the activation of several downstream signaling pathways, including MAPK/ERK, PI3K/AKT/mTOR, and NF-κB (97), resulting in the activation and proliferation of CLL cells (43) (Figure 2).

The most evident observations for a role of TLR signaling in CLL are increased expression of TLR9 in CLL cells compared to healthy B cells (98, 99), TLR pathway activation in LN CLL cells as shown by gene array studies (19, 24), as well as in situ proximity ligation assay experiments that showed the interaction of pIκBα with TLR9 and MYD88 in LN CLL cells (24). CLL BCR specificity for DNA or antigens physically linked to DNA further suggest a role for TLR signaling in driving CLL (8). Moreover, apoptosis-associated antigens bound by sIgs can also be recognized by TLRs after entrance to the endosomal compartment via sIgs (52). Interestingly, the observation that um-CLL cells are more responsive to BCR activation than m-CLL cells is mirrored by TLR activation in vivo and in vitro (24). A possible explanation is that the antigen-specific BCRs in m-CLL make them less likely to internalize antigen-linked TLR ligands compared to um-CLL, whose BCRs are polyreactive and bind with low affinity to a wide variety of antigens (52, 54, 100). Yet, this does not hold for CpG stimulation in vitro, as these are internalized in a BCR-independent fashion. See below in the section in vitro TLR signaling for additional observations that TLR and BCR signaling may cooperate to promote CLL proliferation in um-CLL.

The absence of TIR8, a negative regulator of TLR signaling, was shown to accelerate disease progression in TCL1 mice (101). Moreover, epidemiological studies found an increased risk for the development of CLL following episodes of sinusitis, pharyngitis, influenza, cellulitis, and herpes zoster, where risk increased with increasing severity or frequency of infection (102–104). These studies suggest that infectious agents can promote disease onset and progression of CLL, which may be related to TLR activation (102).

It is not yet clear to what extent these non-BCR signals contribute to proliferation in situ, but it is apparent that both BCR, CD40, and TLR activation all show marked similarities in the downstream signaling pathways involved, including the MAPK/ERK, PI3K/AKT/mTOR, and NF-κB pathways (43) (Figure 2). Perhaps a combination of stimuli is what may really drive CLL proliferation in vivo or helps develop it into more aggressive disease.

in vitro TLR signalling 
In Vitro TLR Signaling

In vitro activation of TLR signaling is carried out using CpG, resulting in endocytosis and subsequent binding of TLR9 in the endosomal compartment, thereby mimicking the interaction of CLL cells with bacteria (120). In vitro stimulation with CpG activates p-p65 and decreases IRAK1 levels, recapitulating the effects of TLR activation as observed in LN CLL cells in vivo (24). In vitro stimulation of CLL cells with CpG resulted in quite variable reports of proliferation (99, 107, 121, 122). Similar to in vitro BCR activation, um-CLL cells can more often be induced to proliferate upon CpG stimulation (97, 123). Importantly, response is not correlated with TLR9 mRNA or protein expression (97). The in vitro proliferative response to CpG was found to be highly predictive of progression-free survival, time to treatment and overall survival in m-CLL, whereas prognosis of um-CLL was equally worse, with or without proliferative response to CpG in vitro (124). Although we still do not fully understand the mechanistic basis of TLR signaling in CLL proliferation, these findings do support the relevance of TLR signaling in driving CLL.

In vitro CpG stimulation was shown to upregulate CD122, which is a shared subunit of the receptor for IL-2 and IL-15 (125). Consistently, addition of the T cell cytokine IL-2 significantly enhances CpG-mediated proliferation of CLL cells (7). IL-15, produced by monocytes, synergistically promotes CpG-mediated CLL proliferation independent of CLL mutation status, thus reversing the difference as usually seen between um-CLL and m-CLL (8, 107). Moreover, in vitro proliferation mediated by CpG/IL-15 could not be linked to prior treatment or in vivo growth rates. As for genetic abnormalities, only TRI-12 was associated with a significantly greater propensity for proliferation in response to CpG/IL-15 (8). Examples of robust in vitro proliferation of clones with slow in vivo growth rates support the notion that the availability of stimulatory signals within the in vivo microenvironment may be as relevant as a cell’s intrinsic potential for proliferation (8). Notably, the abundant presence of IL-15-expressing cells in LNs of CLL patients makes this mechanism clinically relevant (125). Similar to CD40 stimulation, CpG induces upregulation of the IL-21 receptor (126). Whereas healthy B cells proliferated much more than CLL cells following single CpG stimulation, addition of IL-21 rescued enhanced the proliferative activity of CLL cells to the same level of healthy B cells (123).

Links between TLR and BCR signaling have also been described, as for example in vitro stimulation of CLL cells with CpG induced phosphorylation of CD79A, LYN and SYK which appears to rely on the expression of ZAP-70 (127). The strong association between CpG-mediated CLL proliferation and IGHV mutation status may suggest that TLR stimulation is modulated by BCR signaling (97, 123). For example, anergic cells that are usually m-CLL and lack expression of ZAP-70, show reduced proliferative responses to CpG in vitro (124). Studies have shown that engagement of TLR signaling in CLL is able to mount an autocrine feedback loop involving the production and secretion of IgM leading to activation of the cell’s own BCR, which reinforces the concept of tonic BCR signaling in the absence of antigen (107, 127) (Figure 3).

Similar to in vitro BCR activation, stimulation with CpG also caused upregulation of CD40 on CLL cells, showing links of TLR stimulation with CD40 signaling as well (99, 122, 128, 129). Activation of TLR9 via CpG significantly increased CLL proliferation when combined with CD40 stimulation, similar to CD40/IL-21 stimulation (6, 7, 128, 130). Importantly, combined TLR/CD40 stimulation overcomes the hyporesponsiveness to CpG as often seen in m-CLL (130). On the contrary, CLL cells that do not proliferate in vitro in a T-cell dependent manner, can be triggered to proliferate upon addition of CpG/IL-2 (93).

Finally, inhibition of BCR signaling via treatment with ibrutinib or via inhibition of SYK significantly inhibits both CD40- and CpG-mediated CLL proliferation in vitro, showing the role of BCR-associated kinases (36, 107, 131). CD40 and CpG-induced proliferation do however differ in their involvement of the BCR complex. CD40 involves the recruitment of BTK independent of upstream BCR components whereas CpG indirectly triggers the BCR via IgM secretion (107). Therefore, BCR-targeted agents effectively target the aforementioned TLR-BCR feedback loop (107).

Concerning the potential cooperation of signaling pathways, it is important to note that a divergence exists between crosstalk of separate pathways and active rewiring of distinct signaling pathways. For example, in diffuse large B cell lymphoma it was found that the GC and ABC subsets depended on the BCR subunits CD79A/B, but engaged divergent downstream signaling pathways (132). In patients with MYD88 mutations, a new complex consisting of TLR9 and MYD88 was found, revealing interactions with the BCR subunits CD79A/B. It was shown that TLR and BCR signaling cooperate to assemble MYD88 in a signalosome which activates mTOR and NF-κB signaling, providing a mechanistic insight as to why these patients were particularly sensitive to the BCR-targeted agent ibrutinib. This same rewiring was not found in CLL samples, but the expression of ZAP-70 represents another example where single activation of TLR9 is sufficient to fully engage BCR signaling (127, 132). ZAP-70 therefore represents an important candidate for signaling pathway rewiring in CLL. It was shown that TLR-mediated BCR activation was not dependent on the kinase activity of ZAP-70, which is compatible with ZAP-70 functioning as a scaffold in a signaling complex that relays TLR9 signals to SYK, thereby integrating innate into adaptive immune responses (42, 127). However, studying rewiring of signaling pathways is difficult and usually requires techniques such as mass spectrometry or proximity ligation assays to study the interactome of proteins, as ultimately protein-protein interactions assemble and regulate signaling pathways (133). Finally, multiomic analyses allow to study changes in signaling networks under specific conditions, and a novel kinomics approach applied in CLL revealed that rewiring of signaling pathways is not strictly oncogenic but can also be influenced by therapy (134). Comparison of kinase fingerprints between treatment-naïve patients and patients who had undergone prior chemoimmunotherapy, revealed SYK as a critical kinase to be differentially active upon BCR stimulation which correlated with proliferative capacity in vitro (134).

In summary, various crosstalk mechanisms between BCR, CD40, and TLR signaling have been described in CLL based on receptor expression levels, the activation of downstream mediators as well as the use of targeted inhibitors (Figure 3).

Invitro BCR signalling: 
In Vitro BCR Signaling

Despite the consensus regarding the role of BCR signaling in the biology of CLL, the response of CLL cells to BCR stimulation in vitro is notoriously heterogeneous among patient samples (43). In vitro BCR stimulation of CLL cells is performed using anti-IgM, either soluble or immobilized. In vitro responses to BCR stimulation differ between um-CLL and m-CLL as demonstrated by several groups using multiple assays, including global protein tyrosine phosphorylation, gene expression profiling, cellular metabolic activity, apoptotic response and proliferative activity (29–31). Several studies have reported that response to BCR stimulation was correlated with sIgM levels (31). Some studies found higher sIgM levels in um-CLL (108), whereas others found little to no differences between um-CLL and m-CLL (39, 46), claiming a role for additional factors contributing to BCR responsiveness (39). Many studies showed a correlation of CD38 and ZAP-70 expression with BCR responsiveness, however, CD38 does not influence BCR signaling in vitro and ZAP-70 is not required for response. Therefore, these correlations most likely do not result from functional interactions, but are a result of um-CLL expressing higher levels of CD38 and ZAP-70 (39). Some discrepancies found in literature concerning in vitro responses to BCR stimulation can, at least partially, be attributed to the lack of a standardized protocol to trigger the CLL BCR in vitro (109). For example, it has been shown that immobilized anti-IgM provides a more potent in vitro CLL stimulus than soluble anti-IgM (109, 110).

Another possibility is that the variability in BCR responses stems from variable degrees of sIg clustering, which may be associated with natural genomic heterogeneity in BCRs and/or response to antigen (71). Indeed, induction of stable BCR clustering on healthy B cells modulated BCR responsiveness. In fact, by titrating the amount of anti-IgM crosslinking, healthy B cells could be induced to recapitulate the diversity in signaling observed in CLL cells, confirming that BCR clustering can modulate BCR responsiveness and thereby phenocopy the signaling dysfunction in CLL (71). As for the heterogeneity of BCR responsiveness, CLL cells could be divided into 3 subgroups of SHP-1low/pPLCG2high to SHP-1high/pPLCG2low expression, where each subset displayed unique deviations in their BCR signaling responses (71). As increasing levels of SHP-1 and decreasing levels of pPLCG2 correlated with weakened BCR responsiveness, this suggests that phenotypic variability within isogenic populations of cells may result from heterogeneous levels of signaling regulators (71).

Whereas BCR stimulation of healthy B cells significantly induces their proliferation, in vitro BCR stimulation of CLL cells does not lead to proliferation (107), which is another reminder that the in vitro CLL systems are missing a crucial aspect that is active in patients. In vitro engagement of the BCR in CLL promotes G1 cell cycle progression as shown by increased levels of cyclin D2 and CDK4, but does not induce cell division, associated with constitutively high levels of the cell cycle inhibitor p27 (30). Accordingly, CLL cells within proliferation centers of the LN showed high expression of cyclin D2 and downregulation of p27 (111). Therefore, CLL proliferation may depend on costimulatory signals such as those delivered through CD40 or TLRs, possibly in combination with cytokines (6, 7, 16). The interleukins are a family of cytokines that serve as key regulatory elements within the immune system and a number of specific interleukins have been identified as being associated with the proliferation of CLL cells in vitro (43). Importantly, IL-4 promotes the expression and function of surface IgM in CLL cells, thereby enhancing in vitro BCR responsiveness (112). However, proliferation of CLL cells has been mostly described in an antigen-independent context using combined stimulations with CD40L/IL-21, CD40L/CpG, or CpG/IL-15 (107), which we will describe in the next sections.





Other ME singals startify patients: The functional in vitro response to CD40 ligation reflects a different clinical outcome in patients with chronic lymphocytic leukemia https://www.nature.com/articles/leu2011149


GEnetic resistance to BCR inhibition is well reserached, ME-induced resistance much less so: 
[@tenHacken2016]
Mutations in BTK and PLCγ2 were identified through whole-exome sequencing of peripheral blood samples from patients experiencing relapse after ibrutinib treatment, including a cysteine-to-serine mutation at position 481 in BTK (C481S) leading to a protein product with reduced kinase activity, that is only partially inhibited by ibrutinib [179, 180], and three putative gain-of-function mutations in PLCγ2, including arginine-to-tryptophan at position 665 (R665W), leucine to phenylalanine at position 845 (L845F) and serine to tyrosine at position 707 (S707Y) [179].

Woyach JA, Furman RR, Liu TM, Ozer HG, Zapatka M, Ruppert AS, Xue L, Li DH, Steggerda SM, Versele M, Dave SS, Zhang J, Yilmaz AS, Jaglowski SM, Blum KA, Lozanski A, Lozanski G, James DF, Barrientos JC, Lichter P, Stilgenbauer S, Buggy JJ, Chang BY, Johnson AJ, Byrd JC. Resistance mechanisms for the Bruton’s tyrosine kinase inhibitor ibrutinib. The New England journal of medicine. 2014;370:2286–2294. 
180. Fegan C, Bagshawe J, Salles G, Karlin L, Rule S, Shah N, Morschhauser F, Terriou L, Dyer MJ, Walter H, Hutchinson C, Cartron G, Sharpe J, Duffy K, Nishimura A, Abe S, Honda H, Yasuhiro T, Yoshizawa T, Birkett J, Courtenay-Luck N. The Bruton’s Tyrosine Kinase (BTK) Inhibitor ONO-4059: Promising Single Agent Activity and Well Tolerated in Patients with High Risk Chronic Lymphocytic Leukaemia (CLL) Blood (ASH annual meeting abstracts) 2014;124:3328.

Certain studies have shown in vivo evidence of ME activity, but quite lacking: 
 
 
 Soluble CD14 is a novel monocyte-derived survival factor for chronic lymphocytic leukemia cells, which is induced by CLL cells in vitro and present at abnormally high levels in vivo
Martina Seiffert,
Angela Schulz,
Sibylle Ohl,
Hartmut Döhner,
Stephan Stilgenbauer,
Peter Lichter
Crossmark: Check for Updates
Blood (2010) 116 (20): 4223–4230.
https://doi.org/10.1182/blood-2010-05-284505

NLC cells in vivo:[@tenHacken2019]
cNLCs an be found in situ in lymphoid organs from CLL patients [33, 34]. Gene expression 
profile analyses of CLL cells after CLL-NLC co-culture showed that NLCs activate the 
BCR and nuclear factor kappa B (NF-κB) signaling pathways in CLL cells [35]; similar 
gene signatures were identified in CLL cells isolated from lymph nodes of patients [36], 
demonstrating that NLCs are a valid model for studying the CLL microenvironment

and they promote CLL disease progression in vivo in mouse models of CLL [38, 39].
38. Troeger A, Johnson AJ, Wood J, Blum WG, Andritsos LA, Byrd JC, Williams DA. RhoH is critical for cell-microenvironment interactions in chronic lymphocytic leukemia in mice and humans. Blood. 2012;119:4708–4718. [PMC free article] [PubMed] [Google Scholar]
39. Reinart N, Nguyen PH, Boucas J, Rosen N, Kvasnicka HM, Heukamp L, Rudolph C, Ristovska V, Velmans T, Mueller C, Reiners KS, Pogge von Strandmann E, Krause G, Montesinos-Rongen M, Schlegelberger B, Herling M, Hallek M, Fingerle-Rowson G. Delayed development of chronic lymphocytic leukemia in the absence of macrophage migration inhibitory factor. Blood. 2013;121:812–821. [PubMed] [Google Scholar]


endothelial cells and FDCs:
[@tenHacken2016]:
Reciprocal cross-talk between CLL cells and FDCs via the 
ten Hacken and Burger Page 4
Biochim Biophys Acta. 
CXCR5-CXCL13 and the lymphotoxin beta receptor (LTβR)/lymphotoxin alpha beta 
(LTαβ) signaling pathways is essential for CLL positioning within lymphoid follicles and 
for leukemia progression in vivo in the EμTCL1 mouse model of CLL [66]

[66]66. Heinig K, Gatjen M, Grau M, Stache V, Anagnostopoulos I, Gerlach K, Niesner RA, Cseresnyes Z, Hauser AE, Lenz P, Hehlgans T, Brink R, Westermann J, Dorken B, Lipp M, Lenz G, Rehm A, Hopken UE. Access to follicular dendritic cells is a pivotal step in murine chronic lymphocytic leukemia B-cell activation and proliferation. Cancer discovery. 2014;4:1448–1465.

signals: 
High levels of CXCR4+ cells have been associated with higher risk of lymphoid organ infiltration and poorer disease outcome [84], as well as higher responsiveness to BCR stimulation [85].

84. Calissano C, Damle RN, Hayes G, Murphy EJ, Hellerstein MK, Moreno C, Sison C, Kaufman MS, Kolitz JE, Allen SL, Rai KR, Chiorazzi N. In vivo intraclonal and interclonal kinetic heterogeneity in B-cell chronic lymphocytic leukemia. Blood. 2009;114:4832–4842. [PMC free article] [PubMed] [Google Scholar]
85. Coelho V, Krysov S, Steele A, Sanchez Hidalgo M, Johnson PW, Chana PS, Packham G, Stevenson FK, Forconi F. Identification in CLL of circulating intraclonal subgroups with varying B-cell receptor expression and function. Blood. 2013;122:2664–2672. [PubMed] [Google Scholar]


A role of the tissue microenvironment in the pathogenesis of CLL is hypothesized based on in vitro observations, but its contribution in vivo remains ill-defined. Not much is knwon, Herishanu paper attempts to look at samples direclty form in vivo tissues and map gene expression:
To elucidate the effects of tumor-host interactions in vivo, we purified tumor cells from 24 treatment-naive patients. Samples were obtained concurrently from blood, bone marrow, and/or LN and analyzed by gene expression profiling. 
Ibrutinib response and enlarged lymph nodes 


HOw good is our model> 
from Modeling the Leukemia
Microenviroment In Vitro
Cristina Scielzo1* and Paolo Ghia
Not only the microenvironmental interactions but also the 3D
structure itself are considered key for cell proliferation,
differentiation and mobility, as they occur in the context of
cancer development (4). In addition, animal models are
expensive, time consuming and may not adequately reproduce
the features of human tumors, present the correct immune
activation or predict drug responses. In vitro 3D tissue models
could provide a third approach that bridges the gap between
traditional 2D culture and animal models (5). 

3d is better;
In the case of CLL, the most relevant, and indeed the most
utilized cells in co-culture systems, are stromal and nurse-like
cell (NLC). Stromal co-culture systems were first described by
Panayiotidis et al. in 1996. They showed that culturing CLL cells
in contact with BMSCs could increase the percentage of viable
cells after 10 days of culture by more than 30% compared to
controls. Similarly, CLL cells incubated in vitro with FDCs were
protected from spontaneous apoptosis as a result of the ligation
of CD44 on CLL cells and up-regulation of MCL1, a member of
the BCL2 family of anti-apoptotic proteins (28). Later, the same
positive effect in terms of leukemic cell survival in vitro has been
demonstrated with different BM stromal cells (29). In other
instances, in an attempt to simplify the culture systems and avoid

he use of different types of cells, investigators have tried to
replace the pro-survival effect delivered by stromal cells with
single or multiple factors thought to be relevant. Among many
tested, the most utilized have been: CXCL12, CD40L, and IL-4, to
prolong CLL cell survival (30); anti-IgM to increase BCR and
NF-kB signaling and overall activation of the leukemic cells; CpG
(with or without IL-2) to induce proliferation besides prolonging
survival (31).

After a thorough evaluation, alone and in
combination, of several cell-extrinsic factors known to affect
survival and growth of CLL cells, the authors proposed an
optimized co-culture setting with sustained viability and
proliferation of CLL cells, resembling what may occur within
the infiltrate tissues in vivo. The combination includes: a cellular
adherent component (HS5 - BM derived stromal cells), soluble
factors such as CpG + IL2 and the addition of human serum, CLL
plasma and erythrocyte fraction.
However, all these systems are per se limited in the possibility
to fully reproduce the situation and the events occurring in vivo
due to the intrinsic limitations of a flat, 2D culture.

Over the last few
years, a number of 3D culture systems have been designed and
developed and this has been evidenced by the increasing number
of publications on this topic (33)

In the broadest sense, 3D cell cultures can be categorized into two
distinct types: scaffold-based or scaffold-free. Scaffold-based
models support anchorage dependent growth and supporting
structures are made of polymeric hard materials or hydrogels. In
contrast, scaffold-free systems enable anchorage independence
cell growth such us in the context of spheroid obtained by
hanging drop microplates, magnetic levitation or ultra-low
attachment coatings (33).
As an example of the latter models. Farinello et al. set up a
scaffold-free co-culture to form a lymphoid aggregate to study
murine CLL cells and stromal cells interactions by using collagen
to promote the formation of so-called spheroids.
espite the improvements, 3D models have limitations due
to the static condition of the culture system that cannot
reproduce the dynamic interactions occurring in vivo. They are
still lacking the possibility to study ex vivo CLL cells in a dynamic
fashion with the possibility to study phenotypic or functional
changes not only in time but also in space, during trafficking and
homing to and from different tissue microenvironments.
In vivo cell growth is influenced by gravity, different flow
regimes, shear and mechanical stresses. In addition, cells need an
appropriate and continuous oxygen and nutrient transport to

really mimic the in vivo situation. To this end, to have a
functional vasculature system becomes crucial when planning
the design of a viable 3D dynamic model. Thus, an additional
level of complexity is needed to recreate the natural physiology of
the tissue environment through the addition of a dynamic
component to the in vitro system.
An example has been reported by Walsby and collaborators
that developed an interesting in vitro dynamic system that
modeled circulation and allowed for detailed study of
transendothelial extravasation and migration of CLL cells (42)
Achieving this further step of complexity is feasible by using
bioreactors or microfluidic devices

Where are thhe gaps in our knowlrdg, whats needed? 
from Proliferative Signals in Chronic Lymphocytic Leukemia; What Are We Missing?
Marco V. Haselager
In vitro BCR triggering, in contrast, leads to low-level activation and does not result in cell division. Various combinations of non-BCR signals delivered via co-stimulatory receptors, Toll-like receptors (TLRs), and/or soluble cytokines are applied, leading to comparatively modest and short-lived CLL proliferation in vitro. Thus, an unresolved gap exists between the condition in the patient as we now understand it and applicable knowledge that can be harnessed in the laboratory for future therapeutic applications. Even in this era of targeted drugs, CLL remains largely incurable with frequent relapses and emergence of resistance. Therefore, we require better insight into all aspects of CLL growth and potential rewiring of signaling pathways. We aim here to provide an overview of in vivo versus in vitro signals involved in CLL proliferation, point out areas of missing knowledge and suggest future directions for research.


Cytokine concentrations
However, accurately mimicking the cytokine milieu in vitro is complex given that variation in levels and the balance between different cytokines is also
likely to make significant difference to the biology of CLL cells in vitro

in vivo evidenceneeds to be expadned: 
Tumor
cells in proliferation centers become larger and have increased
expression of downstream targets of the BCR signaling, NF-kB
activation, cytokines, and antiapoptotic and proliferation-related
markers.46,49-51 The expansion and high proliferation of these
centers are associated with more aggressive behavior of the
disease.52,53

46. Hartmann EM, Rudelius M, Burger JA,
Rosenwald A. CCL3 chemokine expression
by chronic lymphocytic leukemia cells
orchestrates the composition of the microenvironment
in lymph node infiltrates. Leuk
Lymphoma. 2016;57(3):563-571.

49. Herreros B, Rodr´ıguez-Pinilla SM, Pajares R,
et al. Proliferation centers in chronic lymphocytic
leukemia: the niche where
NF-kappaB activation takes place.
Leukemia. 2010;24(4):872-876.
50. Herishanu Y, Pe´ rez-Gala´n P, Liu D, et al. The
lymph node microenvironment promotes
B-cell receptor signaling, NF-kappaB activation,
and tumor proliferation in chronic
lymphocytic leukemia. Blood. 2011;117(2):
563-574.
51. Gibson SE, Leeman-Neill RJ, Jain S, Piao W,
Cieply KM, Swerdlow SH. Proliferation centres
of chronic lymphocytic leukaemia/small
lymphocytic lymphoma have enhanced expression
of MYC protein, which does not
result from rearrangement or gain of the
MYC gene. Br J Haematol. 2016;175(1):
173-175.
52. Gine´ E, Martinez A, Villamor N, et al.
Expanded and highly active proliferation
centers identify a histological subtype of
chronic lymphocytic leukemia (“accelerated”
chronic lymphocytic leukemia) with aggressive
clinical behavior. Haematologica. 2010;
95(9):1526-1533.
53. Ciccone M, Agostinelli C, Rigolin GM, et al.
Proliferation centers in chronic lymphocytic
leukemia: correlation with cytogenetic and
clinicobiological features in consecutive patients


Future direction: 
from ReviewNF-kB activation in chronic lymphocytic leukemia: A point ofconvergence of external triggers and intrinsic lesionsLarry Mansouria, Nikos Papakonstantinoua,b, Stavroula Ntoufaa,b,Kostas Stamatopoulosa,b, Richard Rosenquista
Several lines of research have established that CLL is all aboutcommunication. Multiple pathways are implicated in this funda-mental process which lies at the core of CLL cell survival andproliferation and the eventual clonal behavior and patient outcome.Presently, their precise intertwining as well as potential deregula-tion by cell-intrinsic aberrations characteristic of CLL, especiallyupon disease progression, are not fully uncovered. That notwith-standing, the fact that most prosurvival/proliferation signals andpathways revolve around/converge on NF-kB  highlights its seminalrole in the natural history of CLL. Realizing this, it becomes ratherunsatisfying that we still have a limited understanding of the bal-ance between external triggers and internal defects and how thismay impact on NF-kB activity; an additional cause for concern isthe lack of clinically meaningful ways to directly inhibitNF-kB  sig-naling in CLL. The potential clinical value of such development ismade all the more evident by the remarkable efficacy of drugs tar-geting one of the pathways converging on NF-kB  i.e. BcR signalinginhibitors.Taken together, further research is clearly warranted along boththe genetic/epigenetic and the immune signaling axis in CLL havingNF-kB  as a major focus and aiming at uncovering critical nodes fortargeted (and combined) pathway inhibition with major therapeu-tic implications for improved management of this still incurabledisease

Read AML paper discussion 


Gernal discussion about hte importance of understanding the microenvrionemtn - taht pergaphhs currenrt drug measurements are rendered obsolete, hew management of CLL, why we need stuides like this, why we need a concerted effort form the community and having this as an open resource shouhdlrpove useful: 
Despite much advancement in chronic lymphocytic leuke- mia (CLL) therapy during the last decade it is still considered an incurable disease. Improvements in understanding treat- ment options, by using drug combinations such as fludara- bine, cyclophosphamide and rituximab (FCR), have led to improved progression-free survival (PFS) and overall survival (OS), but complete response (CR) rates remain disappoint- ingly low and relapse is inevitable [1]. This is perhaps due to an inadequate understanding of the biology of this disease.
Indeed, CLL has relatively belatedly been considered as heterogeneous in its course, its potential origins and its underlying cytogenetics and mutations, after other hemato- logical malignancies were sub-classified in this way. Nonethe- less, momentum is building and recent years have witnessed many studies that have interrogated the biology of CLL.
It has become recognized that CLL has to be considered as a compartmentalized disease. Key compartments include cells localized to the bone marrow (BM) and the lymph nodes (LN) where they receive signals from the microenvironment that, to varying degrees, both sustain disease progression in the absence of treatment and provide assisted drug resistance during therapy. Not surprisingly, studies aimed at under- standing these microenvironments and their consequence on CLL cell survival have become key areas of research. Excit- ing studies by Messmer et al. [2] and van Gent et al. [3] utiliz- ing heavy water have gone a long way to prove these concepts and demonstrate that CLL should be functionally considered as a two-tiered disease, involving a quiescent fraction pres- ent in peripheral blood (PB) and a proliferating tumor load within the solid tissue microenvironments. They have pro- vided dynamic measurements of the fact that the as-yet-to-be fully defined processes within the solid tissue microenviron- ments continually add cell numbers to the total body pool that is reflected by increasing numbers in the blood. However, despite their now commonly accepted critical role in CLL, the involvement of the LN and BM microenvironments have yet to be appropriately considered when developing new treatment strategies. It becomes increasingly likely that the many in vitro drug studies on peripheral CLL cells alone are not likely to translate in a patient to a cure (although they may still have patient benefit). On this basis, many are calling for therapies to be targeted more toward the real enemy of CLL – the tissue microenvironment. An important sub-text to this question is the relative contribution to disease mediated by the LN and BM microenvironments. This review will argue the importance of the LN involvement over that in the BM and how this impinges on treatment strategies.
(from Rachel E. Hayden, Guy Pratt, Claudia Roberts, Mark T. Drayson & Chris M. Bunce (2012) Treatment of chronic lymphocytic leukemia requires targeting of the protective lymph node environment with novel therapeutic approaches, Leukemia & Lymphoma, 53:4, 537-549, DOI: 10.3109/10428194.2011.610014)


Theh lymph node is important - we need to understand more what is giong on in there - single cell seq offeres this opportunity: 
Rachel E. Hayden, Guy Pratt, Claudia Roberts, Mark T. Drayson & Chris M. Bunce (2012) Treatment of chronic lymphocytic leukemia requires targeting of the protective lymph node environment with novel therapeutic approaches, Leukemia & Lymphoma, 53:4, 537-549, DOI: 10.3109/10428194.2011.610014 (read section on lymphnodes versus bone marrow, can take references from there)

LNis also site of MRD: (from Hayden 2012)
Minimal residual disease (MRD), defined as the small num- bers of leukemic cells that remain in the patient during or after treatment when the patient is in remission, occurs in all leu- kemias. Not surprisingly, it is considered to be a major cause of relapse. In other hematological malignancies, for example CML, eradication of MRD is considered the key to long-term remission [122]. Perhaps owing to the milder course of CLL, MRD has only recently come into focus in this setting. 
Attempts at eradicating MRD using ofatumumab [128], lenalomide [127] and most notably alemtuzumab [124,125] have shown superior remission rates compared to chloram- bucil [124]. However, such results were achieved in patients with little or not enlarged LNs, whereas patients with LNs in excess of 5 cm remained MRD-positive [124]. 
It is increasingly clear that the real target of MRD and for ensuring longer remission and ideally achieving cure is the LN niche. Not only is the LN a proven site for CLL propaga- tion, but PB CLL cells can re-enter the LN to both recom- mence proliferation and seek refuge from apoptotic stimuli [89,96]. Many are united in the belief that therapies can no longer simply be directed at the peripheral load, reducing the number of CLL cells in the blood, and that new thera- pies must eliminate CLL cells from the LN, either directly or by targeting known accessory cells/signals, in order to be successful [30,52,53,61,68,84,93,101,129,130]. 
[124] Moreton P, Kennedy B, Lucas G, et al. Eradication of minimal residual disease in B-cell chronic lymphocytic leukemia after alemtuzumab therapy is associated with prolonged survival. J Clin Oncol 2005;23:2971–2979. 
[125] Hillmen P, Skotnicki AB, Robak T, et al. Alemtuzumab compared with chlorambucil as first-line therapy for chronic lymphocytic leukemia. J Clin Oncol 2007;25:5616–5623.
[126] Motta M, Wierda WG, Ferrajoli A. Chronic lymphocytic leukemia: treatment options for patients with refractory disease. Cancer 2009;115:3830–3841. 
[127] Chanan-Khan A, Miller KC, Musial L, et al. Clinical efficacy of lenalidomide in patients with relapsed or refractory chronic lymphocytic leukemia: results of a phase II study. J Clin Oncol 2006;24:5343–5349. [128] Coiffier B, Lepretre S, Pedersen LM, et al. Safety and efficacy of ofatumumab, a fully human monoclonal anti-CD20 antibody, in patients with relapsed or refractory B-cell chronic lymphocytic leukemia: a phase 1-2 study. Blood 2008;111:1094–1100. 
[89] Packham G, Stevenson F. The role of the B-cell receptor in the pathogenesis of chronic lymphocytic leukaemia. Semin Cancer Biol 2010;20:391–399. 
[96] Vogler M, Butterworth M, Majid A, et al. Concurrent up-regulation of BCL-XL and BCL2A1 induces approximately 1000-fold resistance to ABT-737 in chronic lymphocytic leukemia. Blood 2009;113:4403–4413. 
[30] Coscia M, Pantaleoni F, Riganti C, et al. IGHV unmutated CLL B cells are more prone to spontaneous apoptosis and subject to environmental prosurvival signals than mutated CLL B cells. Leukemia 2011;25:828–837. 
[52] Herishanu Y, Perez-Galan P, Liu D, et al. The lymph node microenvironment promotes B-cell receptor signaling, NF-kappaB activation, and tumor proliferation in chronic lymphocytic leukemia. Blood 2011;117:563–574. 
[53] Vandewoestyne ML, Pede VC, Lambein KY, et al. Laser microdissection for the assessment of the clonal relationship between chronic lymphocytic leukemia/small lymphocytic lymphoma and proliferating B cells within lymph node pseudofollicles. Leukemia 2011;25:883–888. 
[61] Patten PE, Buggins AG, Richards J, et al. CD38 expression in chronic lymphocytic leukemia is regulated by the tumor microenvironment. Blood 2008;111:5173–5181. 



[68] Scielzo C, Ten Hacken E, Bertilaccio MT, et al. How the microenvironment shapes chronic lymphocytic leukemia: the cytoskeleton connection. Leuk Lymphoma 2010;51:1371–1374.
[84] Jak M, Mous R, Remmerswaal EB, et al. Enhanced formation and survival of CD4 􏰀 CD25hi Foxp3 􏰀 T-cells in chronic lymphocytic leukemia. Leuk Lymphoma 2009;50:788–801.
[93] Hayden RE, Pratt G, Drayson MT, et al. Lycorine sensitizes CD40 ligand-protected chronic lymphocytic leukemia cells to bezafibrate- and medroxyprogesterone acetate-induced apoptosis but dasatanib does not overcome reported CD40-mediated drug resistance. Haematologica 2010;95:1889–1896. 
[101] Munk Pedersen I, Reed J. Microenvironmental interactions and survival of CLL B-cells. Leuk Lymphoma 2004;45:2365–2372.
[129] Friedberg JW. CLL microenvironment: macro important. Blood 2011;117:377–378.
[130] Hertlein E, Triantafillou G, Sass EJ, et al. Milatuzumab immunoliposomes induce cell death in CLL by promoting accumulation of CD74 on the surface of B cells. Blood 2011;116:2554–2558. 

Cite ac ouple of succesful strategies to target lhmpy node - see section in Hayden paper 


The Hayden paper also disccsuses the fact that CLL is treateable , but alsmot always incurabel, MRD, and relapse is inevitable - perhaps starteiges are wrong they just based on do drugs kill the cells, reflected in in vitor studies that do not account for. 

We need to start with invitor work that accounts for this, and start developing strategies to target, with elimiarntion of MRD the ultimate goal here - and to shortentreatment time, they are very harsh
Get accross the concept that this is a dieases of two compartments - peripheral and an almost solid - like tumour that needs more effectiv targeting

Pathwyas converge on NFKB - via BCR, TLD and CD40 (you can get jsut sgromal cells and CD40 plus a cocktail) thsi is also reflected in our data - these induce strong restaince - perhaps we need to target from multiple anlges - becuase they are compensatory - this might be whats hapenied with IL4 and BCR 


If we cant get rid of ME, then thearpies need to be more sustainable for long perisods, to supress the peripheral population : (from HAyden)
Maintenance therapy aimed at inhibiting the proliferative capacity could be suffi- cient to sustain clinically significant long-term remissions. In this paradigm, therapy would aim to reduce peripheral disease via apoptosis and prevent re-emergence by prevent- ing significant proliferation in the LN, thus maintaining the remissive state [1]. Certainly reduction of the peripheral cells can already be achieved with current therapy such as FCR; however, the associated toxicities preclude its use as a long- term treatment, especially in the largest cohort of patients: those over age 65. Nevertheless, keeping the LN proliferation suppressed long term without eradication of disease would equally require ongoing long-term treatment, and thus
Lymph nodes in chronic lymphocytic leukemia 545a
546 R. E. Hayden et al.
require the use of non-toxic therapies. Drug combinations such as bezafibrate and medroxyprogesterone acetate, which we have investigated, have been shown to induce apoptosis in resting CLL cells and successfully reduce the proliferation of CLL cells in contact with CD40L [97], and have excellent safety profiles [121]. In the absence of available low toxicity treatments that clearly ablate LN-resident MRD we would advocate that these and other low toxicity agents capable of the same activities warrant testing in CLL as potential maintenance therapy. If successful, such regimens could be considered as front-line therapy to halt disease progression and abrogate the need for further therapy, especially in those with a milder disease course.


Targeting BCR and TLR axis via multipe routes, perhaps ibrutinib response is only partial because this is compensated by ibrutib. our data recaptilate muchof this - TLr repsonse canbe inhbitedby ibrutinb 

TLR Signaling Is Activated in Lymph Node-Resident CLL Cells and Is Only Partially Inhibited by Ibrutinib
Eman L Dadashian  1 , Erin M McAuley  1 , Delong Liu  2 , Arthur L Shaffer 3rd  3 , Ryan M Young  3 , Jessica R Iyer  1 , Michael J Kruhlak  4 , Louis M Staudt  3 , Adrian Wiestner #  1 , Sarah E M Herman #  5
Affiliations

    PMID: 30498085 PMCID: PMC6342512 DOI: 10.1158/0008-5472.CAN-18-0781 

Free PMC article
Abstract

Chronic lymphocytic leukemia (CLL) is a malignancy of mature B cells driven by B-cell receptor (BCR) signaling and activated primarily in the lymph node. The Bruton's tyrosine kinase (BTK) inhibitor ibrutinib effectively inhibits BCR-dependent proliferation and survival signals and has emerged as a breakthrough therapy for CLL. However, complete remissions are uncommon and are achieved only after years of continuous therapy. We hypothesized that other signaling pathways that sustain CLL cell survival are only partially inhibited by ibrutinib. In normal B cells, Toll-like receptor (TLR) signaling cooperates with BCR signaling to activate prosurvival NF-κB. Here, we show that an experimentally validated gene signature of TLR activation is overexpressed in lymph node-resident CLL cells compared with cells in the blood. Consistent with TLR activation, we detected phosphorylation of NF-κB, STAT1, and STAT3 in lymph node-resident CLL cells and in cells stimulated with CpG oligonucleotides in vitro. CpG promoted IRAK1 degradation, secretion of IL10, and extended survival of CLL cells in culture. CpG-induced TLR signaling was significantly inhibited by both an IRAK1/4 inhibitor and ibrutinib. Although inhibition of TLR signaling was incomplete with either drug, the combination achieved superior results, including more effective inhibition of TLR-mediated survival signaling. Our data suggest an important role for TLR signaling in CLL pathogenesis and in sustaining the viability of CLL cells during ibrutinib therapy. The combination of ibrutinib with a TLR pathway inhibitor could provide superior antitumor activity and should be investigated in clinical studies. SIGNIFICANCE: CLL relies on the concomitant cooperation of B-cell receptor and Toll-like receptor signaling; inhibition of both pathways is superior to inhibition of either pathway alone. GRAPHICAL ABSTRACT: http://cancerres.aacrjournals.org/content/canres/79/2/360/F1.large.jpg.

Other studies have also shown microenvironmentally-induced gene signatures in lymph-node resident cells [@Herishanu2011], including one study demonstrating that TLR signalling is active in lymph nodes and only partially inhibited by ibrutinib [@Dadashian2019]. 