# Acknowledgements {-}
> "It always seems impossible until it's done."
>
> `r tufte::quote_footer('--- Nelson Mandela')`

I am very grateful to everyone that has supported me over the last four years, and I would like to thank people for helping me to achieve this PhD. 

First and foremost, I would like to thank my PhD Supervisors Dr. Wolfgang Huber and Prof. Dr. Sascha Dietrich. Wolfgang, you have been en excellent mentor and I have learned so much for your approach and patience. Thank you for . You have lead by example, and your approach to science, and your collegiately are skills that I aim take into the rest of my career. Sascha, I learned so much from your approaches. It has been so valuable to work closely with you and the other medics, and help ensure that our research is guided so closely by the clinic. 

In addition to my supervisors, I have benefited hugely from the generous input of other mentors. Thank you for Prof. Dr. Michael Boutros, Dr. Nassos Typas, and Dr. Simon Anders for their enthusiasm in engaging with my project at each TAC meeting, and for their valued advise and expertise that has guided my project so sucessfully. Thank you to Michael for offering to referee this thesis.  I would also like to thank Dr. Mortiz Gerstung, not only for his valued input in all of my TACs (when we both got the right time zone!)  but also for supporting me in my time as a visitng studnet in Cambridge. Thank you for your, I really appreciate the time you have given to engage with my project and to support my science (and the insder knowledge about the Covid-19 situation in the UK and Germany). 

I would also like to thank all members of the Huber, Dietrich and Gerstung groups, past and present. It has been so rewarding to work with such motivated, intelligent and supportive scientists. Thank you to the Huber group for many enjoyable and productive lunch times, coffee breaks in the cafeteria and  fabulous retreats, and of course thank you for all the support and input you have given me in group meetings, and in answering my many questions. To Mike and Junyan , I had almost no experience in R when I began, and I am very grateful that you you took the time to teach me good practice and answer my questions at any tie of the day. I thank Gosia for her useful advice on how to approach this thesis, her R package has also been so useful for this project. I am very grateful to Simone for all her support with the administrative side of my PhD, and to always be on hand as a reassuring voice. Thank you to Junyan and Katharina for genourisluy offering to read my thesis and provide invaluable feedback. 

Thank you to the Dietrich group for our regular lunch time chats (and giving me some German practice) and above all for the support you have provided, especially when I was trying out new techniques in the lab! I would like to thank my colleague Dr. Peter-Martin Bruch: I learned a great deal from you and the project has benefited from your medical and experimental expertise. Thank you to Mareike, Angela, Caro and Tina, your support with experiments (and patience with me in the lab) has been invaluable. 

I am grateful to the Gerstung group for welcoming me over the final 6 months of this project, I have appreciated your input during our retreat, and our regular morning calls and evening meet -ups that have kept me going as I have written this thesis. 

My development as a PhD student and this project have also hugely benefitted form working with collaborators and the tehcnical support and adivce they have provided. Thorsten Zenz and the Zenz group have provided essential input and infrastructure for this project and I have enjoyed our retreats and monthly meetings. Judith Zaugg and the Zaugg group have been very genours with their time an expertise. I am very grateful to Ivan and Christian for their support with my project: I am glad to have been the first user of diffTF, thank you for taking the time to teach me! Thank you also to Brian and Anna, you took the time to show me your experimental techniques in ATACseq and scATACseq and I have been able to share this with the Dietrich labs. Thank you also to Nils Kurzeua, your input in group meetings and siport with building this thesis have been so hoefuly! 

I would like to thank everyone who provided resouces for this project, in particular Dr. Martina Seiffert who provided the HS-5 stromal cell line and Dr. Sophie Herbst for the proteomics dataset. Thank you to each of the aptients how gave their consent for blood samples to be icnluded in this study, it would not have bee possible without their support. 

I am so glad to have had the opportunity to work at such ... Institues and I would like to thank EMBL Heidelberg  for providing the opprotuty to undertakt this PhD, and providing such a fulfilling environment in which to work. Moving abroad was a big step to take, and I could not have been more supported than I have been at EMBL Heidelberg. In particular, the infrastructure at EMBL is so succesful at fostering cutting-edge science, and I would like to thank the Gene Core and Proetomics Core Facilities, the Centre for Statistical ANalysis and EMBL IT services for their help with experiments, data management and analysis. Thank you also to the Molecular Medicine Partnership Unit (MMPU), for providing the infrastructure supporting such a close collaboration between my two labs and to the DKFZ/Heidelberg Center for Personalized Oncology (DKFZ/HIPO) for technical support.

Thank you also to  EMBL-EBI, for hosting me for the final six months of my PhD. The opportunity to work and study in Cambridge has been so positive, and proven invaluable in networking and building the next stages of my life and career. Its provided a haven during a difficult year of lockdowns and travel restrictions. 

My time in Cambridge has been made more productive and enjoyable through the generousity of Dr Hunt and Dr Helena Browne who have supported me as a vistor at Christ's College. I have enjoyed working in the library to write this thesis, and the opportunity to be part of the MCR community here has been invaluable during this time. 

This project would not have been possible without the funding received from the Department of Medicine V, University of Heidelberg, the Molecular Medicine Partnership Unit (MMPU), EMBL Heidelberg  DKFZ/Heidelberg Center for Personalized Oncology (DKFZ/HIPO) for funding, 
and the SIMONA grant. I would also like to recognise the Joachim-Herz Stiftung for their financial support. This project and my development as a PhD student has benefited hugely from the funding  and the networking opportunities the Stiftung has provided. In particular, I am grateful to have been able to spend six months in Cambridge as part of my PhD.  

My PhD has been a huge learning curve, not only in terms of the skills I have learned as a scientist, but also more generally. Moving abroad, undertaking a PhD, learning a new language, getting my first flat, managing remote working, balancing work and life have all been both challenging and hugely rewarding. I am so grateful to my family and friends for supporting me in these steps, and much of this success is shared with them. I would like to thank all of my Heidelberg friends, I have so enjoyed navigating these challenges together, and P11 and Schwarze Peter got us through! Dr. Jakob Wirbel, thank you for helping settle into Germany, even from the very first time we walked what felt like the entirety of Heidelberg during interview week (and of course thank you for guarding my flat all this time!). Dr. Tim Fuqua and Dr. Martine Ballinger, thank you for being my fellow English-speaking pals, I miss all of our late night Guest house chats, dinners at Illegally Tasty, advice and laughs. Thank you to Sally-Jane for your mentorship and advice, it has been invaluable.  Thank you to all my UK friends who have also been there along there way, and visited many times in the last four years, and particularly during the last six months. Kesh, Henry, Adam, thank you for your morale-boosting trips to Cambirdge. Thank you to Michael and Helena, our PhD chats have really go me through the last year, and  thank you to our lockdown zoom gang, Michael, Helena, Vivek, Hollie, Harriet, Kashif, Fergus we could not have got through Winter of 2020 without that! I would also like to recognise the entire catalogues of Coldplay, London Grammar and Pete Tong for being there in the good times, and helping to get through the tougher times.

Finally, and importantly, I would like to thank my family for all the support and mentorship they have provided during the course of my PhD, we did it together. Milly, I am so glad you could live with me for a year in Heidelberg. Jim and Ann, I have appreciated your morale-boosting trips over to Cambridge while I have been writing this thesis, and of course for your venture to Heidelberg and the infamous trip to the castle via the stair case. Mum and Dad, thank you so much for your patience and positivity (and lifting skills), and for always keeping me on the right track. 