---
output:
  pdf_document: default
  html_document: default
---
# List of Abbreviations {-}

\begin{tabular}{rp{0.2cm}lp{1cm}rp{0.2cm}l}
    AML & & Acute myeloid leukaemia \\
    AKT & & Protein kinase B \\
    ATACseq & & Assay for Transposase-Accessible Chromatin using sequencing \\
    ATP & & Adenosine triphosphate \\
    AUC & & Area under curve \\
    BAFF & & B cell-activating factor \\
    BCR & & B-cell receptor \\
    BH & & Benjamini-Hochberg \\
    BMSC & & Mesenchymal bone marrow stromal cell \\
    BTK & & Bruton’s tyrosine kinase \\
    CD40L & & CD40 Ligand \\
    CDF & & Cumulative Distribution Function \\
    ChIPseq & & Chromatin immunoprecipitation sequencing \\
    CLL & & Chronic lymphocytic leukemia \\
    CNV & & Copy number variation \\
    CpG ODN & & CpG oligodeoxynucleotides \\
    DMSO & & Dimethyl sulfoxide  \\
    DNA & & Deoxyribonucleic acid  \\
    DNAseq & & DNA sequencing \\
    ERK & & Ras-dependent extracellular signal-regulated kinase \\
    FACS & & Flourescence-activated cell sorting \\
    FBS & & Fetal bovine serum \\
    FDA & & Federal Drug Administration \\
    FDC & & Follicular dendritic cell \\
    FDR & & False discovery rate \\
    GSEA & & Gene set enrichment analysis  \\
    HS-5 CM & & HS-5 Conditioned Medium  \\
    IFN$\gamma$ & & Interferon$\gamma$   \\ 
    
\end{tabular}
\newpage   
\begin{tabular}{rp{0.2cm}lp{1cm}rp{0.2cm}l}
    
    
  Ig & & Immunoglobulin \\
    IGHV & & Immunoglobulin heavy chain variable region \\
    IHC & & Immunohistochemistry \\
    IL & & Interleukin \\
    JAK & & Janus kinase \\
    M-CLL & & CLL with somatic hypermutations in IGHV loci \\
    U-CLL & & CLL without somatic hypermutations in IGHV loci \\
    MACS & & Magnetic-activated cell sorting \\
    MAPK & & Mitogen-activated protein kinase  \\
    MRD & & Minimal residual disease  \\
    MSCs & & Mesenchymal stromal cells  \\
    NF$\kappa$B & & Nuclear factor kappa-light-chain-enhancer of activated B cells \\
    NLC & & nurselike cell  \\
    NOTCH & & Neurogenic locus notch  \\
    OS & & Overall survival \\
    PBMC & & Peripheral blood mononuclear cells \\
    PCA & & Principal component analysis \\
    PKC & & Protein kinase C \\
    PLC-$\gamma$2 & & phospholipase C $\gamma$ 2 \\
    PI3K & & Phosphoinositide 3-kinase \\
    RNA & & Ribonucleic acid  \\
    RNAseq & & RNA sequencing \\
    SDF1$\alpha$ & & Stromal Cell-Derived Factor-1 alpha  \\
    SF3B1 & & Splicing factor 3B subunit 1 \\
    STAT & & Signal transducer and activator of transcription \\
    
\end{tabular}
\newpage
\begin{tabular}{rp{0.2cm}lp{1cm}rp{0.2cm}l}

  SYK & & Spleen tyrosine kinase \\
    TF & & Transcription factor \\
    TGF$\beta$ & & Transforming growth factor $\beta$ \\
    Th cell & & T-helper cell \\
    TLR & & Toll-like receptor \\ 
    TSS & & Transcription start site \\
    TTFT & & Time to first treatment \\
    TTT & & Time to next treatment \\
    U-CLL & & CLL without somatic hypermutations in IGHV loci \\
    VST & & Variance Stabilising Transformation \\
    WES & & Whole exome sequencing \\
    WGS & & Whole genome sequencing \\
    WT & & Wild type \\
    ZAP70 & & Tyrosine-protein kinase ZAP-70 \\

\end{tabular}
