---
output:
  pdf_document: default
  html_document: default
---
# List of other contributions and achievements {-}

#### Conference Talks and Posters {-}
I have additionally presented the work in this thesis at the following meetings  
\begin{itemize}
  \item  19th International EMBL PhD Symposium 2017
  \item  MMPU Collaboration Meeting 2018
  \item  ASCONA Statistics for Medical Data Science 2019
  \item  MMPU Collaboration Meeting 2019
\end{itemize}


#### Courses and Conferences {-}
During my PhD, I attended the following courses and conferences: 
 
\begin{itemize}
  \item \textbf{2017}
  \item Huber Group Retreat, Dubrovnik \textit{12th - 15th Sept 2017}
  \item EMBL EIPP Predoc Course, Heidelberg \textit{1st Oct - 15th Dec 2017}
  \item EMBL PhD Symposium, Heidelberg \textit{19th - 21st Oct 2017}
  \item \textbf{2018}
  \item Huber-Dietrich SOUND retreat, Black Forest \textit{19th - 20th Feb 2018}
  \item EMBL Biocomputing Retreat, Black Forest \textit{19th - 21st Mar 2018}
  \item EMBL Course: Statistical Methods in Bioinformatics, Heidelberg \textit{25-27th Apr 2018}
  \item EMBL Course: Gitlab, Heidelberg \textit{Apr 2018}
  \item EMBL Course: Using the Cluster, Heidelberg \textit{May 2018}
  \item Quantitative Genomics Conference, London \textit{14th Jun 2018}
  \item EMBL Genome Biology Retreat, Boppard \textit{21st - 22nd Jun 2018}
  \item CSAMA Bioinformatics Course, Brixen \textit{9th - 13th Jul 2018}
  \item EMBL Course: ATACseq Analysis, Heidelberg \textit{10th - 14th Sept 2018}
  \item Lymphoid Malignancies Conference, Dublin \textit{29th - 30th Sept 2018}
  \item EMBL Predoc Retreat, Pilsen \textit{4 - 5th Oct 2018}
  \item MMPU Winter Research Day, Heidelberg \textit{16th Nov 2018}
  \item EMBL PhD Symposium, Heidelberg \textit{21st - 24th Nov 2018}
  \item EBI Bioinformatics Course, Cambridge \textit{26th Nov - 2nd Dec 2018}
  \item \textbf{2019}
  \item EMBL Biocomputing Retreat, Black Forest \textit{18th - 20th Feb 2019}
  \item Therapeutic targeting of the Tumour Microenvironment in Leukemia, London
\textit{24th - 26th Feb 2019}
  \item EMBL Genome Biology Retreat \textit{28th - 29th Mar 2019}
  \item MASAMB (Mathematical and Statistical Aspects of Molecular Biology),
Cambridge \textit{25-26th Apr 2019}

  \item MMPU Summer Research Day, Heidelberg \textit{10th May 2019}
  \item Huber Group Retreat, Mallorca \textit{20th - 24th May 2019}
  \item ASCONA 2019: Statistics for Medical Data Science \textit{17th - 21st Jun 2019}
  \item EMBL Course: Corporate Winter School, Heidelberg \textit{Sept 2019 and Feb 2020}
  \item 1st Translational Research E-Conference, Chronic Lymphocytic Leukemia
\textit{16-19th Nov 2020}
  \item American Society for Haematology Annual Meeting & Exposition \textit{7 - 10th Dec 2020}

\end{itemize}

#### Software {-}
During my PhD, I have been committed to open science and have published the following software: 
\begin{itemize}
  \item \textbf{\underline{Giles, Holly A. R.}} and Peter M. Bruch, 2021. CLLCytokineScreen2021: Complete data and executable scripts to reproduce the figures and analysis presented in Bruch and Giles et al. 2021. https://github.com/Huber-group-EMBL/CLLCytokineScreen2021
  
  \item \textbf{\underline{Giles, Holly A. R.}} 2021. CLLCytokineScreen2021Shiny: Shiny app to explore the dataset presented in Bruch and Giles et al. 2021. https://www.imbi.uni-heidelberg.de/dietrichlab/CLL_Microenvironment/
\end{itemize}

#### Responsibilities
\begin{itemize}
  \item \textbf{Coordinator, EMBL PhD Symposium 2018} My role as Coordinator involved managing a team of 30 PhD students to plan and implement a large-scale conference, with over 220 attendees and a budget of over \euro{60000}. 
  \item \textbf{External Consultant, Merck KGaA} In this role I advised Merck regarding the implementation of the project proposal I submitted as part of Team Healthy Lives at the 2018 Merck Innovation Cup..
\end{itemize}


#### Awards 
\begin{itemize}
  \item \textbf{Joachim-Herz Add-on Fellowship for Interdisplinary Life Science 2019}, \euro{12000} In 2019 I was awarded the Joachim-Herz Add-on Fellowship funds interdisciplinary research and qualification (e.g. stays at a research lab and participation in conferences) over a period of two years.
  \item \textbf{Merck Innovation Cup}, \euro{5000} As part of a team of six, I competed in the anniversary edition of the Merck Innovation Cup, winning first prize in the Healthy Lives category, for our business proposal for a new pharmaceutical product to improve our preparedness for future viral pandemics.
\end{itemize}


