---
output:
  pdf_document: default
  html_document: default
---
# Zusammenfassung {-}
Die chronische lymphatische Leukämie (CLL) ist eine bösartige Erkrankung reifer B-Lymphozyten, die durch eine Anhäufung bösartiger Zellen im Blut, Knochenmark und in den Lymphknoten gekennzeichnet ist. Die Krankheit nimmt einen heterogenen Verlauf, der durch mehrere Faktoren bestimmt wird, darunter genetische Aberrationen, die Signalübertragung über den B-Zell-Rezeptor (BCR) und Interaktionen mit nicht-neoplastischen Zellen in der Mikroumgebung des Tumors. Viele einzelne Krankheitsfaktoren wurden bereits gut charakterisiert, und die CLL ist eine Erfolgsgeschichte, wenn es darum geht, Fortschritte im molekularen Verständnis mit Verbesserungen bei den klinischen Ansätzen zu verknüpfen. Darauf aufbauend versprechen Multi-omiks-Ansätze, unser Verständnis der Krankheitsbiologie durch die Integration verschiedener Datentypen zu verbessern.  Im klinischen Bereich besteht nach wie vor die Notwendigkeit, ein systematisches Verständnis der Rolle zu entwickeln, die genetische Aberrationen und Signalwege gemeinsam bei der CLL spielen.

In dieser Arbeit untersuche ich den Einfluss zelleigener und -fremder Faktoren auf die Biologie der CLL und das Ansprechen auf Medikamente. Ich verwende einen Datensatz, der aus Lebensfähigkeitsdaten von CLL-Primärproben besteht, die mit Arzneimitteln und Stimuli aus der Mikroumgebung behandelt wurden, sowie aus molekularen Profilen derselben Proben. Der Lebensfähigkeitstest wurde mit 12 Medikamenten durchgeführt, die jeweils mit 17 individuellen Mikroumweltstimuli kombiniert wurden (n = 192), und mit molekularen Profilen kombiniert, die Punktmutationen, Kopienzahlvariationen, DNA-Methylierung und mRNA-Expression umfassen. Ergänzt wird der Datensatz durch klinische Patientendaten und immunhistochemische (IHC) Färbungen von Lymphknotenbiopsien.  Ich wende statistische Schlussfolgerungen und Regressionsmodellierung an, um mehrere wichtige Erkenntnisse zu gewinnen.
 
Erstens zeigen CLL-Proben heterogene Reaktionen auf die verschiedenen Stimuli aus der Mikroumgebung, wobei IL4 und TLR-Signalisierung den stärksten Einfluss haben. Aus den Reaktionsprofilen lassen sich vier Patientenuntergruppen ableiten, die unterschiedliche Krankheitsdynamiken und molekulare Profile aufweisen. Zweitens: Eine systematische Untersuchung der genetischen Determinanten der Mikroumweltreaktion identifiziert Trisomie 12 als einen wichtigen Modulator. Die Daten deuten darauf hin, dass die Transkriptionsfaktoren Spi-B und PU.1 diese Wirkung vermitteln können. Drittens erstelle ich eine Karte der Wechselwirkungen zwischen Mikroumwelt-Signalwegen und Arzneimitteln und identifiziere neue Wege der Arzneimittelresistenz, einschließlich der Wirkung von IFN$\gamma$ auf die Toxizität von Ibrutinib. Ich zeige, wie diese Wechselwirkungen zwischen Medikament und Mikroumgebung durch molekulare Merkmale weiter moduliert werden können, und identifiziere kontextabhängige Mechanismen der Medikamentenresistenz, die bei bestimmten genetischen Hintergründen auftreten. Zum Beispiel induziert die TLR-Aktivität eine Resistenz gegen Fludarabin bei IGHV-U und Trisomie 12 CLLs, aber nicht bei IGHV-M. Schließlich wird die *in vivo* Relevanz dieser Ergebnisse in CLL-infiltrierten Lymphknoten nachgewiesen, die im Vergleich zu nicht-neoplastischen Proben höhere IL4-Signalisierungswerte aufweisen (p<0,001). Erhöhte IL4-Signalisierung in CLL-infiltrierten Lymphknoten korreliert mit schlechteren Behandlungsergebnissen (p=0,038). 

Der vorgestellte Datensatz und die Analyse sind online ([https://github.com/Huber-group-EMBL/CLLCytokineScreen2021](https://github.com/Huber-group-EMBL/CLLCytokineScreen2021)) und über eine interaktive glänzende App ([https://www.imbi.uni-heidelberg.de/dietrichlab/CLL_Microenvironment/](https://www.imbi.uni-heidelberg.de/dietrichlab/CLL_Microenvironment/)) verfügbar. Insgesamt zeigen diese Ergebnisse die Auswirkungen genetischer Aberrationen und mikroökologischer Stimuli auf das Ansprechen auf Medikamente und legen neue pathogene Mechanismen und Ursachen der Medikamentenresistenz nahe.
